# pip-audit configuration
# Document known vulnerabilities and their status

[[tool.pip-audit.ignores]]
# pip 25.2 tarfile extraction vulnerability
# Fix is planned for pip 25.3 but not yet released
# https://github.com/pypa/pip/pull/13550
id = "GHSA-4xh5-x5gv-qwph"
reason = "No fix available yet - planned for pip 25.3. Mitigation: only install packages from trusted sources (PyPI)."
expires = "2025-11-15"  # Review when pip 25.3 is expected to be released

# Note: authlib GHSA-9ggr-2464-2j32 HAS a fix (1.6.4) and should be upgraded
# It is NOT ignored here - upgrade authlib to resolve

# Additional configuration
[tool.pip-audit]
# Fail if vulnerabilities found (except ignored ones)
require-hashes = false
# Scan all dependencies (not just local)
local = false
