# Read the Docs configuration file for XPCS Toolkit
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install poetry if using it for dependency management
      - pip install --upgrade pip setuptools wheel
    post_install:
      # Install any additional system dependencies if needed
      - echo "Build environment setup complete"

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Explicitly set the version of Sphinx and its extensions
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Optional but recommended - specify formats
formats:
  - pdf
  - epub

# Search configuration
search:
  ranking:
    api/: 1
    guides/: 2
  ignore:
    - _build/
    - .git/