name: Documentation

on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'README.rst'
      - 'pyproject.toml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'README.rst'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libegl1-mesa libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]

    - name: Build documentation with Sphinx
      run: |
        cd docs
        make clean
        make html
        # Copy additional markdown docs to html build
        cp DOCUMENTATION_INDEX.md _build/html/
        cp OPTIMIZATION_GUIDE.md _build/html/
        cp LOGGING_SYSTEM.md _build/html/
        cp TESTING.md _build/html/
        cp PRODUCTION_READINESS_FINAL_REPORT.md _build/html/

    - name: Setup Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v3

    - name: Upload artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs/_build/html

    - name: Upload docs artifacts (PR)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: docs-preview-${{ github.event.number }}
        path: docs/_build/html

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

  link-check:
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
    - uses: actions/checkout@v4

    - name: Download built docs
      uses: actions/download-artifact@v3
      if: github.event_name == 'pull_request'
      with:
        name: docs-preview-${{ github.event.number }}
        path: _site

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1
      with:
        args: --verbose --no-progress '_site/**/*.html' --base _site
        fail: false
      if: github.event_name == 'pull_request'