name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'xpcs_toolkit/**/*.py'
      - 'README.md'
      - 'pyproject.toml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'xpcs_toolkit/**/*.py'
      - 'README.md'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[docs]
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        run: |
          cd docs
          sphinx-build -b html -W --keep-going . _build/html
        
      - name: Check documentation links
        run: |
          cd docs
          sphinx-build -b linkcheck . _build/linkcheck

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: documentation
          path: docs/_build/html/
          retention-days: 7

  check-pypi-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine readme-renderer[md]

      - name: Build package
        run: python -m build

      - name: Check README rendering
        run: |
          python -m readme_renderer README.md -o /tmp/readme.html
          echo "✅ README renders correctly for PyPI"

      - name: Check package metadata
        run: |
          python -m twine check dist/*
          echo "✅ Package metadata is valid"